version: '3.8'

#Docker Networks
networks:
  proxy:
    external:
      name: nginx-proxy

# Workflow
services:
  nuxt_main:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    container_name: nuxt_main
    # volumes:
    #   - ./src:/var/www/html:delegated
    restart: always
    ports:
      - "4002:4002"
    command:
      "npm run start"
    networks:
      - proxy